### ISSUE TITLE
Crash: Seemingly incompbatible with Sodium Extras

### ISSUE THREAD

**Issue by Shywizz** [ImCodist/quick-menu#9] opened 2023-08-04 15:35 UTC
After spending way too long identifying which mod was causing a crash upon attempting to open the editing UI it seems that something goes wrong when the following mods are installed 

- Fabric API
- Sodium
- Sodium Extra
- oωo
- Yours, AKA Quick Menu
Unless I wrongly identified a crash, or something totally diffrent is going on.
here is the [full log](https://mclo.gs/63MXW4X)

**Comment by roridev** [comment] 2023-08-04 22:22
Can repro, disabling sodium extra seems to make quick-menu stable. It could be something between owo-lib and sodium extra tho.

**Comment by ImCodist** [comment] 2023-08-05 06:30
Seemingly a problem with owo-lib.
Will attempt to update to the newest version of owo-lib, however it could be something added in my project it specifically dislikes.

Will look into this problem asap.

**Comment by ImCodist** [comment] 2023-08-05 06:30
oops crap im so tired

**Comment by ImCodist** [comment] 2023-08-07 04:18
I am unable to reproduce the crash, even on the modpack you have provided.
Is there a way you can be more specific? Does the crash happen every time or like randomly or something?
Entering edit mode works fine for me.

Closing for now.

**Closed by ImCodist** 2023-08-07 04:18 UTC
Labels: bug
